# Generated by Django 5.2.15 on 2026-06-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name, e.g. Ravi K.', max_length=120)),
                ('role', models.CharField(blank=True, help_text='Business / role shown under the name, e.g. Print Studio', max_length=120)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Star rating (1-5)')),
                ('message', models.TextField(help_text='The review text. Hinglish is fine.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide this review from the website without deleting it.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number shows first. Same numbers fall back to newest first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Review',
                'verbose_name_plural': 'Customer Reviews',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributorInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('business_type', models.CharField(choices=[('print_shop', 'Print shop'), ('reseller', 'Reseller'), ('distributor', 'Distributor'), ('studio', 'Studio'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not shown to the applicant).')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Distributor Inquiry',
                'verbose_name_plural': 'Distributor Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Caption heading, e.g. Ink Lay Test', max_length=120)),
                ('subtitle', models.CharField(blank=True, help_text='Small caption under the title, e.g. Vibrant CMYK+W output', max_length=160)),
                ('video_file', models.FileField(blank=True, help_text='Upload an mp4 video (recommended). It auto-plays on the site.', null=True, upload_to='reels/')),
                ('external_url', models.URLField(blank=True, help_text='Optional: a YouTube or Instagram link (used only if no file is uploaded).')),
                ('poster', models.ImageField(blank=True, help_text='Optional thumbnail image (used for external links).', null=True, upload_to='reel_posters/')),
                ('accent', models.CharField(choices=[('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('violet', 'Violet')], default='cyan', help_text='Border/glow colour for the card (CMYK theme).', max_length=10)),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide this reel from the website without deleting it.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number shows first. Same numbers fall back to newest first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reel Video',
                'verbose_name_plural': 'Reel Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
