# Generated by Django 5.2.15 on 2026-06-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customerreview_distributorinquiry_reelvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_url',
            field=models.URLField(blank=True, help_text='Optional: direct Amazon product link. If empty, an Amazon search link is used.'),
        ),
        migrations.AddField(
            model_name='product',
            name='flipkart_url',
            field=models.URLField(blank=True, help_text='Optional: direct Flipkart product link. If empty, a Flipkart search link is used.'),
        ),
    ]
