# Generated by Django 5.2.15 on 2026-06-26 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_amazon_url_product_flipkart_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amazon_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flipkart_url',
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional MRP shown with a strike-through above the selling price. Leave blank if there is no discount.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main photo — shown first (top) on the product detail page.', null=True, upload_to='products/'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
