# Generated by Django 5.2.15 on 2026-06-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_default_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(help_text="Customer's WhatsApp number.", max_length=20)),
                ('note', models.CharField(blank=True, help_text='Optional: what the customer was looking at (e.g. Rolls savings).', max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('sent', 'Details Sent')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catalog Request (WhatsApp)',
                'verbose_name_plural': 'Catalog Requests (WhatsApp)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dtf_rolls', 'DTF Rolls'), ('dtf_ink', 'DTF Ink'), ('dtf_powder', 'DTF Powder'), ('sublimation_paper', 'Sublimation Paper'), ('project_special', 'Special Product')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('', '— None (Ink / no sub-type) —'), ('single_matte', 'Rolls › Single Matte'), ('double_matte', 'Rolls › Double Matte'), ('standard', 'Powder › Standard'), ('premium', 'Powder › Premium'), ('korean_virgin', 'Sublimation Paper › Korean Virgin Paper'), ('virgin', 'Sublimation Paper › Virgin Paper')], default='', help_text='Only for Rolls, Powder & Sublimation Paper — splits them into quality types. Leave blank for Ink.', max_length=20),
        ),
    ]
