# Generated by Django 5.1.15 on 2026-06-29 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remap_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Just the size value in inches — e.g. "13 x 19", "24" or "36". The "(in inches)" label is shown automatically; no need to type it.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='core.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
