# Generated by Django 5.1.15 on 2026-06-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cartitem_unique_together_cartitem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional MRP (₹) for this size — shown struck-through above the price. Leave blank if this size has no discount.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Selling price (₹) for THIS size. Leave blank to use the product's base price.", max_digits=10, null=True),
        ),
    ]
