# Generated by Django 4.2.30 on 2026-07-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productsize_original_price_productsize_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrequest',
            name='is_seen',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='is_seen',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='distributorinquiry',
            name='is_seen',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_seen',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='stocknotification',
            name='is_seen',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
