# Generated by Django 4.2.30 on 2026-07-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cartitem_is_seen_catalogrequest_is_seen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_seen',
        ),
    ]
