# Generated by Django 4.2.30 on 2026-07-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_catalogrequest_is_seen_contactinquiry_is_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('seen_until', models.DateTimeField()),
            ],
        ),
    ]
